### ISSUE TITLE
GitHub activity chart requires horizontal scrolling on mobile. 

### ISSUE THREAD

**Issue by jelmstrom** [rasmus-eklund/SaltTalentPool#25]
On mobile device, the GitHub activity chart is too wide so you need to scroll horizontally. This means that the data is displayed front and center is from the beginning of the year, and not showing recent activity.

**Comment by allanheremi** [comment]
Hi Johan! Thank you for great feedback.

The issue is now resolved, github contributions container will adjust based on screen size. The whole view should now always be visible.

 Attached image of mobile view below.
<img width="269" alt="image" src="https://github.com/rasmus-eklund/SaltTalentPool/assets/121552608/09996c23-19ec-4483-b538-4fa92a1a689e">
